# Copyright 2021-2023 Intel Corporation
# All rights reserved.
#
# Docker Compose file allowing to build and deploy locally a DAOS virtual cluster

version: "3.8"

services:

  daos_agent:
    image: "daos-agent:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-agent/el8"
      args:
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_UID=${DAOS_CLIENT_UID}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
        - "DAOS_CLIENT_GID=${DAOS_CLIENT_GID}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "RHEL_BASE_IMAGE_NAME=${RHEL_BASE_IMAGE_NAME}"
        - "RHEL_BASE_IMAGE_TAG=${RHEL_BASE_IMAGE_TAG}"
        - "BUST_CACHE=${BUST_CACHE}"
        - "DAOS_REPOS=${DAOS_REPOS}"
        - "DAOS_GPG_KEYS=${DAOS_GPG_KEYS}"
        - "DAOS_REPOS_NOAUTH=${DAOS_REPOS_NOAUTH}"
        - "DAOS_VERSION=${DAOS_VERSION}"
        - "DAOS_ACCESS_POINTS=${DAOS_ACCESS_POINTS}"
        - "DAOS_PORT=${DAOS_PORT}"
        - "DAOS_AUTH=${DAOS_AUTH}"
        - "DAOS_IFACE_CFG=${DAOS_IFACE_CFG}"
        - "DAOS_IFACE_NUMA_NODE=${DAOS_IFACE_NUMA_NODE}"
        - "DAOS_IFACE_NAME=${DAOS_IFACE_NAME}"
        - "DAOS_IFACE_DOMAIN_NAME=${DAOS_IFACE_DOMAIN_NAME}"
    network_mode: host
    pid: host
    volumes:
      - type: volume
        source: daos_agent-socket
        target: /var/run/daos_agent
        volume:
          nocopy: true
    secrets:
      - source: daos_agent-certs
        target: daos_agent-certs.txz

  daos_client:
    image: "daos-client:${DAOS_DOCKER_IMAGE_TAG}"
    build:
      context: "daos-client/el8"
      args:
        - "DAOS_CLIENT_UNAME=${DAOS_CLIENT_UNAME}"
        - "DAOS_CLIENT_UID=${DAOS_CLIENT_UID}"
        - "DAOS_CLIENT_GNAME=${DAOS_CLIENT_GNAME}"
        - "DAOS_CLIENT_GID=${DAOS_CLIENT_GID}"
        - "DAOS_DOCKER_IMAGE_TAG=${DAOS_DOCKER_IMAGE_TAG}"
        - "RHEL_BASE_IMAGE_NAME=${RHEL_BASE_IMAGE_NAME}"
        - "RHEL_BASE_IMAGE_TAG=${RHEL_BASE_IMAGE_TAG}"
        - "BUST_CACHE=${BUST_CACHE}"
        - "DAOS_REPOS=${DAOS_REPOS}"
        - "DAOS_GPG_KEYS=${DAOS_GPG_KEYS}"
        - "DAOS_REPOS_NOAUTH=${DAOS_REPOS_NOAUTH}"
        - "DAOS_VERSION=${DAOS_VERSION}"
    tty: true
    network_mode: host
    pid: host
    user: "${DAOS_CLIENT_UID}:${DAOS_CLIENT_GID}"
    volumes:
      - type: volume
        source: daos_agent-socket
        target: /var/run/daos_agent
        volume:
          nocopy: true
    depends_on:
      - daos_agent


volumes:
  daos_agent-socket:


secrets:
  daos_agent-certs:
    file: "${DAOS_AGENT_CERTS_TXZ}"
